### ISSUE TITLE
Language clarification: client = PLEDGE client

### ISSUE THREAD

**Issue by smasover** [ucberkeley/brc-draft-documentation#3]
Cf. Step 5 at this link: https://github.com/ucberkeley/brc-draft-documentation/wiki/Logging-into-Savio#step-3-download-the-profile-to-your-smartphone-or-computer

Was not clear the "client" referred to the Pledge client just installed. Clarify.

**Comment by aronr** [comment]
We're also using the term "application" and "client" interchangeably, in instructions in Step 3 and elsewhere. We might consider standardizing throughout on "application" (or just "app", which can apply to both smartphone and desktop/laptop).

I'd suggest that the use of the term Pledge "client," while accurate, is specialized jargon and has the potential to confuse some readers.

**Comment by aronr** [comment]
Believed addressed by this refactoring of the wiki docs:
https://github.com/ucberkeley/brc-draft-documentation/wiki/Logging-into-Savio/60cf116ce00c0d1a771ead87f72265c1f67e7fc5

These references have been converted to either *Pledge* or *the Pledge application*, depending on context.
