### ISSUE TITLE
Globus Connect Personal - install instructions give incorrect nav directions

### ISSUE THREAD

**Issue by smasover** [ucberkeley/brc-draft-documentation#33]
In the page https://github.com/ucberkeley/brc-draft-documentation/wiki/Using-Globus-Online-with-Savio this instruction is given re: setting up Globus Connect Personal:

"Click the "Manage Endpoints" link near the top of the home page."

That link is not available on the home page. I sniffed it out by going to Products : Globus Connect and found a link "Get Globus Connect Personal."

I wonder if site navigation changes frequently.

**Comment by aronr** [comment]
Thanks for this report. I'm consistently seeing that option available _as a logged in user_, as per the steps listed in that section:

```
1. If you're not already logged into the Globus website, do so.
2. Click the "Manage Endpoints" link near the top of the home page.
3. Click the "add Globus Connect Personal" link.
...
```
I also tried this as someone who was not logged into their Globus account, and went through the Products section of the website. To set up the endpoint (as contrasted with just downloading the Personal Connect software), you're still asked to log in, and overall you get a more disjointed experience, IMO. And following that route, someone could potentially just download and run the desktop software and then wonder why personal downloads don't just 'automagically' work thereafter, or why transfers can't be initiated via that software.

Will try making the first line (about logging in) clearer, in hopes that this helps avoid this confusion. Let me know what you think?

**Comment by smasover** [comment]
Not sure that's what I'm seeing Aron.

![image](https://cloud.githubusercontent.com/assets/7143639/9534929/6b71c530-4cd1-11e5-923c-eb35e71ccd17.png)

**Comment by aronr** [comment]
Thanks! (Steve and I found that only I was seeing the Manage Endpoints link. We concluded that we'll use the direct link for that page in the doc: https://www.globus.org/xfer/ManageEndpoints
