### ISSUE TITLE
Globus Savio endpoint clarity

### ISSUE THREAD

**Issue by smasover** [ucberkeley/brc-draft-documentation#34]
On the "Transfering Data" page a point is made to connect only to dtn.brc.berkeley.edu.

On the Globus page, the endpoint instruction is: "Enter ucb#brc into the Endpoint field at left. (This is the Globus endpoint for Savio.)"

What's implicit, but not stated, is that this endpoint is properly pointed to/through the DTN. Might it be worth indicating this, e.g.: Enter ucb#brc into the Endpoint field at left. (This is the Globus endpoint for Savio**, on the Data Transfer Node dtn.brc.berkeley.edu**.)

**Comment by aronr** [comment]
Text added, similar to this suggestion.
