### ISSUE TITLE
Must generate new OTP to log in via SSH

### ISSUE THREAD

**Issue by smasover** [ucberkeley/brc-draft-documentation#4]
Cf. https://github.com/ucberkeley/brc-draft-documentation/wiki/Logging-into-Savio#step-5-connect-to-savio-using-ssh

Cannot re-use OTP used to verify that Pledge install and profile download/setup is correct, as language in doc currently implies. Must generate a new OTP. Document should say so explicitly.

Moreover, it would be helpful to note that clicking the generated OTP returns the client to a state in which one can generate a new OTP.

**Comment by aronr** [comment]
Believe addressed in this refactoring of the Logging into Savio document:
https://github.com/ucberkeley/brc-draft-documentation/wiki/Logging-into-Savio/60cf116ce00c0d1a771ead87f72265c1f67e7fc5

Someone following the instructions literally, at least, will be instructed to create a new OTP for their first login to the Savio cluster, and there is no implication - however indirect - that the OTP they created to test their profile can be re-used for that login.

> Moreover, it would be helpful to note that clicking the generated OTP returns the client to a state in which one can generate a new OTP.

Am hoping this new language in the Logging into Savio document addresses that issue, if I'm understanding it correctly:

> If a one-time password is currently being displayed in the Pledge application window, click that password in order to redisplay the Generate one-time password button.
