### ISSUE TITLE
After first device's Pledge install, OTP can be used instead of 10-char password provided by HPC team

### ISSUE THREAD

**Issue by smasover** [ucberkeley/brc-draft-documentation#5]
Cf. https://github.com/ucberkeley/brc-draft-documentation/wiki/Logging%20into%20Savio#step-2-create-a-pledge-profile

This is good for first time through, properly requiring use of a password supplied by the HPC team in a 'manual' process that is part of account setup.

However, on setup of subsequent devices, that password need not be used: instead, a 6-digit OTP can (and should?) be used to obtain a new profile ID for setting up the Pledge client on the new device.

**Comment by aronr** [comment]
Good point, @smasover. (And thanks, @davclark for sharing your experience, as well.)

Am hoping this is adequately addressed by this refactoring of the Logging into Savio document:
https://github.com/ucberkeley/brc-draft-documentation/wiki/Logging-into-Savio/60cf116ce00c0d1a771ead87f72265c1f67e7fc5

Under **Step 2: Create a Pledge profile for your device**, the following wording appears:

> - At the Password prompt, enter your initial 10-digit password.
>  - Tip: Have you already set up Pledge on one of your other devices? If so, rather than entering your initial 10-digit password, you can instead launch the Pledge application on that device, generate a 6-digit one-time password, and enter that one-time password at the Password prompt on the Pledge Enrollment web page.

**Comment by aronr** [comment]
I've noted that LBL's documentation also confirms that an OTP can be used instead of the initial 10-digit password:

https://commons.lbl.gov/display/itfaq/Installing+and+Configuring+the+OTP+Token
(See the "Create Profile" tab.)
